server:
  port: 8000
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: QingxinTutor
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_qingxin_tutor
    username: ENC(09LUbqP4f5OnCK7+UjRyYByGJLMyo72jS8tULPvu3L2004dMO4K94FuQzMYXggol)
    password: ENC(3pfs9B7/cfOzSIfskDMZKHdXHs5y9Vrb5PzK5BBORHYDwoz2+6e496ndHQ3VFGR7)
  data:
    redis:
      host: localhost
      port: 6379
      password: ENC(IgbGe8lD0U1OpgJ/6qjvdI7S+DC0U7FpaefY6Kz9F/3jsvzin9EU5HXtK+38pEpMMOkRfB5AtZevcjE78oNvQA==)
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  mail:
    host: smtp.163.com
    port: 465
    username: ENC(AwZyAZ3LAA5SqNJ4ubyRWYYS8lw9u9SOWXfVCAqhQS3pk2pt4s4+Q5A9KJiBm8tM)
    password: ENC(B5hwxbqIjxHPW3Lt83xDrGUQ4ISvJSzEvePxzo160EueDNhoCCuSnqceoNBR/VXYaBgD3x3kaPPtxcdD1XgI8g==)
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465
          auth: true
          starttls:
            enable: true
        default-encoding: UTF-8
  servlet:
    multipart:
      location: ${UPLOAD_BASE_DIR:${java.io.tmpdir}}/QingxinTutor/multipart-file
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
app:
  oauth:
    github:
      client-id: Ov23lio5To7yiJd7E2PZ
      client-secret: ENC(CnjQJCycGlVKNV1uigOpUBwAa9loEVU5a/pEEprHLZj9m8cDe/4eAkUrf8+ODaM66FFfqtszAEKMizAcO7AUrzepftUF7tdzrFEI5VDH+08=)
      redirect-uri: qingxintutor://github-callback
  jwt:
    secret: ENC(Rr4MPfEWOCuVM2prCThw1Gje7zGgJCqAPufYrnyE+DDX1CRkwz8pgC8hNtF9xhWds8ZHTrCiQ4Z1GvNiCV3hqbzPEna8BAprkXmygfjobCI=)
    expiration: 604800000  # ms
  ai:
    api-key: ENC(OULibtYqvsFCpNJJIzrQpToRZgTklE0GTxCVV3o/4JOUY2MHdmtga+0eyVlG5POoeGaKVb7V9Ktzs3erP6M6u+N0OLDQ8+vc9O/aFU1bE3s=)
    base-url: https://ark.cn-beijing.volces.com/api/v3
    model: doubao-seed-1-6-lite-251015
  upload:
    file-dir: ${UPLOAD_BASE_DIR:${java.io.tmpdir}}/QingxinTutor
jasypt:
  encryptor:
    password: ${JASYPT_KEY}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    provider-name: SunJCE
    key-obtention-iterations: 10000